[package]
name = "beatbank-tauri"
version = "0.6.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.5", features = [] }
criterion = "0.4"

[lib]
name = "beatbank_tauri"
path = "src/lib.rs"

[[bin]]
name = "beatbank-tauri"
path = "src/main.rs"

[dependencies]
rusqlite = { version = "0.32.0", features = ["bundled"] }
tauri = { version = "1", features = [ "protocol-asset", "fs-copy-file", "fs-create-dir", "fs-exists", "path-all", "fs-read-dir", "dialog-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "chrono"] }
diesel_migrations = "2.2.0"
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
tokio = { version = "1", features = ["full"] }
symphonia = { version = "0.5", features = ["mp3", "wav", "flac", "aac"] }
open = "3.2"
aubio = { version = "0.2.1", features = ["bindgen"] }
log = "0.4.22"
env_logger = "0.11.5"
criterion = "0.4"
dirs = "5.0"


[[bench]]
name = "audio_benchmarks"
harness = false
path = "benches/audio_benchmarks.rs"




[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
