# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['audio_analyzer.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
    'altgraph',
    'audioread',
    'certifi',
    'cffi',
    'charset_normalizer',
    'decorator',
    'idna',
    'joblib',
    'lazy_loader',
    'librosa',
    'llvmlite',
    'msgpack',
    'numba',
    'numpy',
    'packaging',
    'pefile',
    'platformdirs',
    'pooch',
    'pycparser',
    'pyinstaller',
    'pyinstaller_hooks_contrib',
    'pywin32_ctypes',
    'requests',
    'scikit_learn',
    'scipy',
    'setuptools',
    'soundfile',
    'soxr',
    'threadpoolctl',
    'typing_extensions',
    'urllib3'
],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='audio_analyzer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
